### ISSUE TITLE
3.12 rebase checklist

### ISSUE THREAD

**Issue by colesbury** [colesbury/nogil#104]
- [ ] ae289ce53e Disable the GIL by default.
- [ ] edc3cffede Use per-thread refcounts for heap type objects
- [ ] c734997c4b Implement new interpreter
- [ ] 11de39ee87 Remove "--with-trace-refs" from configure
- [ ] 59a4843e43 faulthandler: don't dump all threads when running without the GIL
- [ ] fa42f3bc93 json: make JSON scanner thread safe
- [ ] 71823e6d9e signalmodule: fix thread-safety issue on macOS
- [ ] a8ed04a0b7 _struct: fix race condition in cache_struct_converter
- [ ] 31caeb812b module: intern module name
- [ ] d55c608784 sha1: make sha1module thread-safe
- [ ] 6a9619572e stringio: make stringio thread-safe
- [ ] e29f51cbb6 semaphore.c: decrease count before release sem_lock
- [ ] 11de5c8018 importlib: fix data race in imports (PyImport_ImportModuleLevelObject)
- [ ] 80379ce171 deque: make most functions thread-safe
- [ ] 36d9f3c9aa test_gdb: nogil mode fixes
- [ ] 99ec8d4887 textio: add locks to make textio thread-safe
- [ ] 945176f2dc bufferedio: add locks to make print() thread-safe
- [ ] e5e9f2596b clinic: support '@' syntax for recursive mutexes
- [ ] b10476d76b random: add a recursive mutex to guard random.Random
- [ ] 46702d3a4c functools: make lru_cache thread-safe
- [ ] 39dc33ca49 socketmodule.c: use relaxed atomics for global 'defaulttimeout'
- [ ] 7dafcd2eb9 asdl: use _PyOnceFlag in Python-ast.c
- [ ] 0f7a4a28bf object.c: fix race when accessing attributes and methods
- [ ] bf7c7149ce getargs.c: make parser_init thread-safe
- [ ] e891fff93d asyncio: fix race conditions in enter_task and leave_task
- [ ] 212f493e36 _threadmodule: thread-safety fixes
- [ ] eb67b2748a moduleobject: fix data races
- [ ] 8ffd4ceab1 ceval: fix data races in ceval.c
- [ ] 4bcc712534 frame: don't use zombieframe when running without the GIL
- [ ] d3503e92a4 accu: don't acquire list lock when appending
- [ ] 7c2790b622 set: make set thread-safe
- [ ] 17d1edb8c0 list: make list thread-safe
- [ ] 0d331528ec dict: make dict thread-safe
- [ ] c2a54b7685 ordereddict: remove C implementation
- [ ] 90d16587e2 ordereddict: simplify Python implementation
- [ ] c06dbaad27 queue: make SimpleQueue thread-safe
- [ ] a33fcf51b7 Stop the world before fork() and Python shutdown
- [ ] 73af0aecfb gc: implement stop-the-world GC
- [ ] 9c2c881ed2 threading: remove _tstate_lock from threading.Thread
- [ ] 87364a937a typeobject: remove static cache in resolve_slotdups
- [ ] 2642e687c5 typeobject: make method_cache thread-local
- [ ] 68bc87fdad _threadmodule: make _thread.lock thread-safe
- [ ] 66c47e918e codecs.c: fix race condition
- [ ] 4ed4b0955c unicode: make unicodeobject.c thread-safe
- [ ] e7a0521ff4 dtoa: make dtoa thread-safe
- [ ] e390b81964 weakref: make weakrefs thread-safe without the GIL
- [ ] 7d2cb67605 gc: Traverese mimalloc heaps to find all objects.
- [ ] 4778bf9f39 gc: make the garbage collector non-generational
- [x] d8326b0620 obmalloc: use separate mimalloc heaps in obmalloc.c
- [x] d059e29758 mimalloc: tag pages with qsbr counter
- [x] edc7b51d49 mimalloc: don't fill in first N bytes with debug values
- [x] 383f593135 mimalloc: split thread exiting from abandoning heaps
- [x] d340a94863 mimalloc: changes to support separate heaps
- [x] 9a7f2267df mimalloc: minimal changes for use in Python
- [x] c87a2a6ca2 Add mimalloc v1.7.5
- [x] 79d522f093 Create io.BytesIO() in destructor of test_io.py
- [ ] cbbf4d38c0 Disable most free lists
- [x] 6f4617626b Add safe memory reclamation scheme based on FreeBSD's GUS
- [x] ca2a8fdd8f Implement biased reference counting
- [x] 2205f705fd Move _Py_RefTotal to per-thread state
- [x] ~~9c5049d351 Call function when incref/decref~~
- [x] ~~c40dda7f82 Add ob_tid to every object~~
- [x] 50c13031e7 Make global objects immortal (not reference counted)
- [x] 7884d98939 multiprocessing: use CriticalLock in a few places
- [x] 350b0cdfb1 Add _thread.CriticalLock which prevents the current thread from parking
- [x] a03f4f73ee ceval: move eval_breaker to per-thread state
- [x] 3a98232c45 Enable/disable the GIL at runtime
- [x] d1c164e8c7 Change "SOABI" and sys.implementation.name and define Py_NOGIL
- [x] 0951ec4e55 critical_section: helpers for fine-grained locking
- [x] c3272efb8b parking_lot: add mutexes and one-time notifications
- [x] 9bb0733c89 pystate: keep track of attached vs. detached state
- [x] d1aee8abd7 Skip subinterpreter tests that run on "incorrect" thread
- [x] 0b8a36d4f8 Make PyThreadState_GET thread-local
- [x] 9c38274cd9 pyport: add new macros
- [x] bd068acb8a Add pyatomic.h

**Comment by colesbury** [comment]
More recent changes (not all need to be rebased):

- [x] 4de17ac5e9 pyatomic: fix warning on MSVC
- [ ] e7d66cf129 pip: update modified bundled pip
- [ ] 969ec6b2a0 Fix platform.python_compiler()
- [x] 5a7b97eab0 atomic: add bulitin (GCC) atomics
- [x] 22480e770f pyatomic: error when there is atomic implementation
- [ ] 0085e2ce3c Overwite INCLUDEPY and CONFINCLUDEPY
- [ ] 258cab1c76 Update pythonba.vcxproj from upstream CPython
- [ ] ee13015e1a Update windows.yml
- [ ] f0e7b22bf7 Don't compile ceval.s with ceval.o
- [ ] 52e8523021 Add GitHub actions to build Windows and macOS distributions
- [ ] 965e9670fc ceval: Mark functions as always-inlined
- [ ] 4b05376b6d Fix gdb traceback for Python generators
- [ ] f7e45d6bfb Update publish-docker.yml
- [ ] 1761801084 Merge pull request #85 from lesteve/docker-build-push
- [ ] f34229def1 Fix docker tag
- [ ] ca01d13d6b Add github workflow to build and publish docker image
- [ ] 9bb1e2edd1 Pin jinja2 version in Doc/make.bat
- [ ] 44a22d0091 Tools/msi: add buildnogil.bat
- [ ] 49ce508398 bpo-47138: Fix documentation build by pinning Jinja version to 3.0.3 (GH-32153)
- [ ] 0ad343d10a Make small ints immortal
- [ ] 55d895ff81 PCBuild: add missing file 'bitmap.c'
- [ ] 2dcbadc25d frame: fix thread-safety issue when accessing f_lineno
- [ ] 4b358237b4 list: make list_repr thread-safe
- [ ] f3b6e462dc code: improve hash function
- [ ] e664310886 Fix makeopcodetargets.py and generated files after recent changes
- [ ] 8ad4f8aea0 dis: make dis.opmap values be ints instead of Bytecode objects
- [ ] fc44b03fa2 dis: prefer string/const names as "argval"
- [ ] d0dfef6352 code: make co_names an alias for co_consts
- [ ] 411e8494ce docker: fix key issue with NVIDIA CUDA image
- [ ] 463fc64546 code: rename co_framesize to co_stacksize
- [ ] f33857972b pystate: re-init stoptheworld_mutex after-fork
- [ ] 0126b8947b code: use empty tuple when missing some attributes
- [ ] a6976eb0cb tuple: expose _Py_EmptyTuple to limited API
- [ ] 9678b94533 Move critical_section to the limited API
- [ ] b1689ff536 ceval: clean up vm_trace
- [ ] 74e57b70e8 ceval: fix detection of Python function calls
- [ ] e785b9c991 signal: ensure signal handler function is retained across call
- [ ] 6c3895ff21 ceval: add missing cororoutine return trace events
- [ ] 0453fa68bc ceval: fix tracing of C method descriptors when called with varargs
- [ ] ca53bb4573 Update and rename README.rst to README.md
- [ ] 5c35dc0df4 Add "nogil" identifier to Py_GetVersion()
- [ ] bb728e35a9 Add Py_RefCnt function for use from PyO3 fork
- [ ] 87c61c34a1 funcobject: missing Py_INCREF when replacing closure
- [ ] df2ffbdfa3 mimalloc: create Objects/mimalloc build directory during configure
- [ ] f9dbb92afa code: fix bug in code_richcompare
- [ ] df289e6bbf list: fix thread-safety issues in list_ass_slice
- [ ] 9d8a660c2b list: fix thread-safety issue with list slicing
- [ ] 7d1be8bac8 remove duplicate typedefs
- [ ] c3894a5ead pip: use modified bundled pip
- [ ] 895c1244da Add docker files for building nogil Python
- [ ] 0af745b7dd Update README.rst for nogil
